environment:

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
build: off

test_script:
  - make.bat
